// I suspect that repeated letters from multiple lists will give it a
// disproportionately higher show rate, such as i or y. While in development
// perhaps document things like show rate in its own program when doing fine
// adjustments and give that as additional information on the side of the
// project or a timeline of large steps or a part of a Youtube video.

// I think in order to make better words I should probably add more predefined
// bunches of letters that are common, check soybomb

// Here are some more rules to establish for better word generation:
// 1. Check the letters behind the rhymeKey and include any vowels there are.
// 2.

const Consonants = {
  beginning: [
    'b',
    'd',
    'f',
    'ph',
    'g',
    'h',
    'j',
    'c',
    'ch',
    'k',
    'l',
    'm',
    'n',
    'gn',
    'kn',
    'p',
    'q',
    'r',
    'wr',
    's',
    'sc',
    'sh',
    't',
    'th',
    'v',
    'w',
    'wh',
    'y',
    'z',
    'x',
  ],
  middle: [
    'bb',
    'dd',
    'ed',
    'f',
    'ph',
    'g',
    'gg',
    'h',
    'j',
    'ci',
    'c',
    'ch',
    'cc',
    'ck',
    'l',
    'm',
    'mm',
    'n',
    'nn',
    'p',
    'pp',
    'r',
    'rr',
    's',
    'ss',
    'sh',
    'ti',
    't',
    'tt',
    'th',
    'v',
    'w',
    'y',
    'z',
    'zz',
    'x',
  ],
  end: [
    'b',
    'bb',
    'd',
    'dd',
    'ed',
    'f',
    'ff',
    'ph',
    'g',
    'gg',
    'ge',
    'dge',
    'c',
    'k',
    'ck',
    'cc',
    'que',
    'l',
    'll',
    'm',
    'mm',
    'mb',
    'n',
    'nn',
    'ng',
    'p',
    'pp',
    'r',
    'rr',
    's',
    'se',
    'ss',
    'sc',
    'ce',
    'sh',
    't',
    'tt',
    'tch',
    'ed', // maybe remove
    'v',
    've',
    'w',
    'y',
    'z',
    'zz',
    'ze',
    'x',
  ],
  endRhymeGroup: [
    ['b', 'bb'],
    ['bb', 'b'],
    ['d', 'dd'],
    ['dd', 'd'],
    ['ed', 'edd'],
    ['f', 'ff', 'ph'],
    ['ff', 'f', 'ph'],
    ['ph', 'f', 'ff'],
    ['g', 'gg'],
    ['gg', 'g'],
    ['ge'],
    ['dge'],
    ['c', 'k', 'ck', 'cc'],
    ['k', 'c', 'ck', 'cc'],
    ['ck', 'k', 'c', 'cc'],
    ['cc', 'c', 'k', 'ck'],
    ['que'],
    ['l', 'll'],
    ['ll', 'l'],
    ['m', 'mm'],
    ['mm', 'm'],
    ['mb'],
    ['n', 'nn'],
    ['nn', 'n'],
    ['ng'],
    ['p', 'pp'],
    ['pp', 'p'],
    ['r', 'rr'],
    ['rr', 'r'],
    ['s', 'ss'],
    ['se'],
    ['ss', 's'],
    ['sc', 'sk'],
    ['ce'],
    ['sh'],
    ['t', 'tt'],
    ['tt', 't'],
    ['tch'],
    ['ed'], // maybe remove
    ['v', 've'],
    ['ve', 'v'],
    ['w'],
    ['y'],
    ['z', 'zz', 'ze'],
    ['zz', 'z', 'ze'],
    ['ze', 'zz', 'z'],
    ['x', 'xe'],
  ],
  prefix: [
    'non',
    'dis',
    'fore',
    'sub',
    'post',
    'mis',
    'trans',
    'co',
    'mono',
    'semi',
    'homo',
    'pre',
    'mid',
    'tri',
    're',
    'micro',
    'pro',
    'poly',
    'super',
    'macro',
    'hyper',
    'circum',
    'micro',
    'para',
    'therm',
  ],
  suffix: [
    'dom',
    'ment',
    'ness',
    'ship',
    'sion',
    'tion',
    'ful',
    'less',
    'ly',
    'ward',
    'wards',
    'wise',
  ],
  suffixRhymeGroup: [
    ['dom', 'um', 'om'],
    ['ment', 'ent'],
    ['ness', 'ess'],
    ['ship'],
    ['sion', 'un', 'tion'],
    ['tion', 'sion', 'un'],
    ['ful', 'ul'],
    ['less', 'ess', 'est'],
    ['ly'],
    ['ward'],
    ['wards'],
    ['wise', 'wize'],
  ],
}

const Vowels = {
  beginning: [
    'a',
    'au',
    'e',
    'ea',
    'i',
    'o',
    'aw',
    'u',
    'ay',
    'ai',
    'ey',
    'ei',
    'ie',
    'oa', // Maybe get rid of this an bottom one
    'ou',
    'ow',
    'ar',
    'air',
    'ear',
    'are',
    'irr',
    'ere',
    'or',
  ],
  middle: [
    'a',
    'au',
    'e',
    'ea',
    'i',
    'o',
    'aw',
    'ough',
    'u',
    'ay',
    'ai',
    'ey',
    'ei',
    'ea',
    'ee',
    'ie',
    'y',
    'igh',
    'oa',
    'ou',
    'ow',
    'ew',
    'oo',
    'oul',
    'oi',
    'oy',
    'ar',
    'air',
    'ear',
    'are',
    'irr',
    'ere',
    'eer',
    'or',
    'oor',
    'ur',
    'ir',
    'er',
  ],
  end: [
    'a',
    'au',
    'e',
    'ea',
    'i',
    'o',
    'aw',
    'ough',
    'u',
    'ay',
    'ai',
    'ey',
    'ei',
    'ie',
    'ee',
    'y',
    'igh',
    'oa',
    'ou',
    'ow',
    'ew',
    'oul',
    'oo',
    'oi',
    'oy',
    'ar',
    'ear',
    'air',
    'are',
    'irr',
    'ere',
    'eer',
    'or',
    'ore',
    'oor',
    'ur',
    'ir',
    'er',
  ],
  endRhymeGroup: [
    // This group will be accessed through the rhymeKey
    // and will select the corresponding array which includes the original
    // grapheme as a possible rhyme choice. A possible way to fine tune the selection
    // manually is to add more of the desireable choices to increase their appearance rate.
    ['a', 'ah', 'aw', 'au'],
    ['au', 'ow'], // Changed this because I always read au as ow
    ['e'],
    ['ea', 'y', 'i', 'ee', 'ie'],
    ['i', 'ea', 'y', 'ee'],
    ['o', 'ough', 'oe', 'uo', 'o', 'eau'],
    ['aw', 'a', 'ah'],
    ['ough', 'o', 'oh'],
    ['u', 'oo', 'ew', 'ou'],
    ['ay', 'ey', 'uay', 'eigh', 'ei'],
    ['ai', 'igh', 'ye'],
    ['ey', 'ay', 'eigh', 'ei'],
    ['ei', 'ey', 'ay', 'eigh'],
    ['ie', 'i', 'ee', 'ea', 'y'],
    ['ee', 'i', 'ie', 'ea', 'y'],
    ['y', 'ee', 'i', 'ie', 'ea'],
    ['igh', 'ye', 'ai'],
    ['oa', 'o', 'oe', 'ough', 'ou'],
    ['ou', 'oa', 'o', 'ough', 'oe'],
    ['ow', 'o', 'au', 'oe', 'ough', 'oa', 'eau'],
    ['ew', 'oo', 'ou', 'u'],
    ['oul', 'ole', 'oll', 'oal', 'ohl', 'ol'],
    ['oo', 'ew', 'ue', 'eu', 'u'],
    ['oi', 'oy', 'oui'],
    ['oy', 'oi', 'oui'],
    ['ar', 'ahr'],
    ['ear', 'eer', 'ier', 'irr', 'ere'],
    ['air', 'eir', 'are'],
    ['are', 'air', 'eir'],
    ['irr', 'ear', 'ere'],
    ['ere', 'ear', 'eer', 'ier', 'irr'],
    ['eer', 'ear', 'irr', 'ier', 'ere'],
    ['or', 'ore', 'oar', 'oor'],
    ['ore', 'or', 'oar', 'oor'],
    ['oor', 'ore', 'or', 'oar'],
    ['ur', 'er', 'eur'],
    ['ir', 'eer', 'ear', 'ier', 'eir', 'eare'],
    ['er', 'ur', 'urr', 'eur'],
  ],
  prefix: [
    'anti',
    'extra',
    'uni',
    'in',
    'inter',
    'un',
    'ex',
    'over',
    'under',
    'auto',
    'ante',
    'em',
    'en',
    'epi',
    'im',
    'infra',
    'intra',
    'omni',
  ],
  suffix: [
    'acy',
    'al',
    'ance',
    'ence',
    'er',
    'or',
    'ism',
    'ist',
    'ity',
    'ty',
    'ate',
    'en',
    'ify',
    'fy',
    'ise',
    'ize',
    'able',
    'ible',
    'al',
    'esque',
    'ic',
    'ical',
    'ious',
    'ous',
    'ish',
    'ive',
    'y',
  ],
  suffixRhymeGroup: [
    ['acy', 'y', 'ee', 'ea', 'i'],
    ['al', 'aul', 'all'],
    ['ance', 'ants', 'antz', 'anse'],
    ['ence', 'ense', 'ents'],
    ['er', 'ur', 'urr', 'uhr', 'rrh', 'eur'],
    ['or', 'ore', 'oar', 'oor'],
    ['ism', 'isum', 'izm', 'isme', 'izam', 'isholm'],
    ['ist', 'issed', 'idst', 'issed', 'yst', 'iste', 'isced'],
    ['ity', 'ittee', 'itty', 'iti', 'itee'],
    ['ea', 'y', 'ee'],
    ['ate', 'ait', 'aite', 'eight'],
    ['en', 'ehn', 'enn', 'enne', 'enh'],
    ['ai', 'igh', 'ye'],
    ['ai', 'igh', 'ye'],
    ['ise', 'ize', 'ies', 'ighs', 'eiz'],
    ['ise', 'ize', 'ies', 'ighs', 'eiz'],
    ['able', 'abel', 'aybill', 'abal'],
    ['ible', 'ibal', 'ibel'],
    ['al'],
    ['esque', 'esk', 'esc', 'eske'],
    ['ic', 'ick', 'ik'],
    ['ical', 'ycle', 'ichael', 'ikal'],
    ['ious', 'us', 'ous'],
    ['ous', 'us'],
    ['ish', 'iche'],
    ['ive'],
    ['y', 'ee', 'ea'],
  ],
}
