// I suspect that repeated letters from multiple lists will give it a
// disproportionately higher show rate, such as i or y. While in development
// perhaps document things like show rate in its own program when doing fine
// adjustments and give that as additional information on the side of the
// project or a timeline of large steps or a part of a Youtube video.

// I think in order ti make better words I should probably add more predefined
// bunches of letters that are common, check soybomb
const Consonants = {
  beginning: [
    "b",
    "d",
    "f",
    "ph",
    "g",
    "h",
    "j",
    "c",
    "ch",
    "k",
    "l",
    "m",
    "n",
    "gn",
    "kn",
    "p",
    "r",
    "wr",
    "s",
    "sc",
    "sh",
    "t",
    "th",
    "v",
    "w",
    "wh",
    "y",
    "i",
    "z",
    "x"
  ],
  middle: [
    "bb",
    "dd",
    "ed",
    "f",
    "ph",
    "g",
    "gg",
    "h",
    "j",
    "ci",
    "c",
    "ch",
    "cc",
    "ck",
    "l",
    "m",
    "mm",
    "n",
    "nn",
    "p",
    "pp",
    "r",
    "rr",
    "s",
    "ss",
    "sh",
    "ti",
    "t",
    "tt",
    "th",
    "v",
    "w",
    "y",
    "i",
    "z",
    "zz",
    "x"
  ],
  end: [
    "b",
    "bb",
    "d",
    "dd",
    "ed",
    "f",
    "ff",
    "ph",
    "g",
    "gg",
    "ge",
    "dge",
    "c",
    "k",
    "ck",
    "cc",
    "que",
    "l",
    "ll",
    "m",
    "mm",
    "mb",
    "n",
    "nn",
    "ng",
    "p",
    "pp",
    "r",
    "rr",
    "s",
    "se",
    "ss",
    "sc",
    "ce",
    "sh",
    "t",
    "tt",
    "tch",
    "ed",
    "v",
    "ve",
    "w",
    "y",
    "i",
    "z",
    "zz",
    "ze",
    "x"
  ],
  prefix: "something",
  suffix: 0
}

const Vowels = {
  beginning: [
    "a",
    "au",
    "e",
    "ea",
    "i",
    "o",
    "aw",
    "u",
    "ay",
    "ai",
    "ey",
    "ei",
    "y",
    "ie",
    "oa",
    "ou",
    "ow",
    "ar",
    "air",
    "ear",
    "are",
    "irr",
    "ere",
    "or"
  ],
  middle: [
    "a",
    "au",
    "e",
    "ea",
    "i",
    "o",
    "aw",
    "ough",
    "u",
    "ay",
    "ai",
    "ey",
    "ei",
    "ea",
    "ee",
    "ie",
    "y",
    "igh",
    "oa",
    "ou",
    "ow",
    "ew",
    "oo",
    "oul",
    "oi",
    "oy",
    "ar",
    "air",
    "ear",
    "are",
    "irr",
    "ere",
    "eer",
    "or",
    "oor",
    "ur",
    "ir",
    "er"
  ],
  end: [
    "a",
    "au",
    "e",
    "ea",
    "i",
    "o",
    "aw",
    "ough",
    "u",
    "ay",
    "ai",
    "ey",
    "ei",
    "ie",
    "ee",
    "y",
    "igh",
    "oa",
    "ou",
    "ow",
    "ew",
    "oul",
    "oo",
    "oi",
    "oy",
    "ar",
    "ear",
    "air",
    "are",
    "irr",
    "ere",
    "eer",
    "or",
    "ore",
    "oor",
    "ur",
    "ir",
    "er"
  ],
  endRhymeGroup: [
    // This group will be accessed through the rhymeKey
    // and will select the corresponding array which includes the original
    // grapheme as a possible rhyme choice. A possible way to fine tune the selection
    // manually is to add more of the desireable choices to increase their appearance rate.
    ["a", "ah", "aw", "au"],
    ["au", "aw", "ah", "a"],
    ["e", "eh"],
    ["ea", "y", "i", "ee", "ie"],
    ["i", "ea", "y", "ee"],
    ["o", "ough", "ow", "oe", "uo", "o", "eau"],
    ["aw", "a", "ah"],
    ["ough", "o", "oh", "ow"],
    ["u", "oo", "ew", "ou"],
    ["ay", "ey", "uay", "eigh", "ei"],
    ["ai", "igh", "ye"],
    ["ey", "ay", "eigh", "ei"],
    ["ei", "ey", "ay", "eigh"],
    ["ie", "i", "ee", "ea", "y"],
    ["ee", "i", "ie", "ea", "y"],
    ["y", "ee", "i", "ie", "ea"],
    ["igh", "ye", "ie", "i"],
    ["oa", "o", "oe", "ow", "ough", "ou"],
    ["ou", "oa", "o", "ough", "ow", "oe"],
    ["ow", "o", "au", "oe", "ough", "oa", "eau"],
    ["ew", "oo", "ou", "u"],
    ["oul", "ole", "oll", "oal", "ohl", "ol"],
    ["oo", "ew", "ue", "eu", "u"],
    ["oi", "oy", "oui"],
    ["oy", "oi", "oui"],
    ["ar", "ahr"],
    ["ear", "eer", "ier", "irr", "ere"],
    ["air", "eir", "are"],
    ["are", "air", "eir"],
    ["irr", "ear", "ere"],
    ["ere", "ear", "eer", "ier", "irr"],
    ["eer", "ear", "irr", "ier", "ere"],
    ["or", "ore", "oar", "oor"],
    ["ore", "or", "oar", "oor"],
    ["oor", "ore", "or", "oar"],
    ["ur", "er", "eur"],
    ["ir", "eer", "ear", "ier", "eir", "eare"],
    ["er", "ur", "urr", "eur"]
  ],
  prefix: 0,
  suffix: 0
}
